name: citadel
author: Arron Washington
description: A sample web application
version: 0.0.1
dependencies:
  browser: any
  crypto: any
  game_loop: any
  js: any
  json: any
  logging: any
  path: any
  route: any
  stagexl: any
  tmx: any
  unittest: any
  xml: any
  yaml: any
